# 0) IMPORTS

In [1]:
# Setup autoreload - automatically reload modules when they change
%load_ext autoreload
%autoreload 2

In [2]:
# Verify environment setup
import os
import sys

print(f"Python version: {sys.version}")
print(f"Python executable: {sys.executable}")
print(f"\nEnvironment variables loaded:")
print(f"OPENAI_API_KEY: {'✓ Set' if os.getenv('OPENAI_API_KEY') else '✗ Not set'}")
print(f"POLYGON_API_KEY: {'✓ Set' if os.getenv('POLYGON_API_KEY') else '✗ Not set'}")
print(f"XAI_API_KEY: {'✓ Set' if os.getenv('XAI_API_KEY') else '✗ Not set'}")

Python version: 3.12.7 (main, Oct  1 2024, 02:05:46) [Clang 16.0.0 (clang-1600.0.26.3)]
Python executable: /Users/realmistic/Documents/stocks-scoring-agent/.venv/bin/python

Environment variables loaded:
OPENAI_API_KEY: ✓ Set
POLYGON_API_KEY: ✓ Set
XAI_API_KEY: ✓ Set

# 1) TEST: Checking news retrieval for the recent 5k records 
* The datasource is Massive.com (previously known as Polygon.io)
* 2 tools defined: 
  * search_news_by_ticker (not just YahooFinance source)
  * search_news_by_query (it can find a wider set of news to expand the topic)

In [3]:
from datetime import datetime, timezone
now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
print (f'Time now = {now}')

# The exact time of running the Colab (in UTC, timezone-aware)
now_right_format = datetime.now(timezone.utc).isoformat(timespec='milliseconds')
print(f'Time now in the right format (for API) = {now_right_format}')

Time now = 2026-06-07
Time now in the right format (for API) = 2026-06-07T12:56:48.846+00:00

In [4]:
import requests
import pandas as pd
import os

# MASSIVE.COM is previously known as Polygon.io
# https://massive.com/docs/rest/stocks/news
# https://massive.com/blog/api-pagination-patterns
# API CALL : # https://api.massive.com/v2/reference/news?order=desc&limit=1000&sort=published_utc&apiKey=<your key> or POLYGON_API_KEY
      # need to get 200 OK status

# check the API KEY is imported correctly from the .envrc file
print(len(f'Length of the POLYGON_API_KEY = {os.getenv("POLYGON_API_KEY")}'))

POLYGON_API_KEY = os.getenv('POLYGON_API_KEY')

# retrieve max 1000 news via one API call
def get_one_chunk_of_news_polygon_io(api_key = POLYGON_API_KEY, news_limit=1000, max_date = now):
#OLD:   url = f"https://api.polygon.io/v2/reference/news?order=desc&limit={news_limit}&sort=published_utc&published_utc.lt={max_date}&apiKey={api_key}"
  url = f"https://api.massive.com/v2/reference/news?order=desc&limit={news_limit}&sort=published_utc&published_utc.lt={max_date}&apiKey={api_key}"


  # https://www.nylas.com/blog/use-python-requests-module-rest-apis/ - Python for rest APIs
  # try/catch for HTTP requests: https://stackoverflow.com/questions/16511337/correct-way-to-try-except-using-python-requests-module
  try:
      url_sanitized = url.split("&apiKey=")[0] + "&apiKey=<your key>"
      print(f'trying the API call : {url_sanitized}')
      r = requests.get(url, timeout=3)
      r.raise_for_status()
  except requests.exceptions.HTTPError as errh:
      print ("Http Error:",errh)
  except requests.exceptions.ConnectionError as errc:
      print ("Error Connecting:",errc)
  except requests.exceptions.Timeout as errt:
      print ("Timeout Error:",errt)
  except requests.exceptions.RequestException as err:
      print ("OOps: Something Else",err)

  data = r.json()


  # Check if 'results' key exists in the response
  if 'results' in data:
      # If it exists, proceed with normalization
      df_nested_list = pd.json_normalize(data, record_path=['results'])
  else:
      # If not, print the response keys for debugging and create an empty DataFrame
      print(f"The 'results' key was not found in the response. Available keys are: {data.keys()}")
      df_nested_list = pd.DataFrame() # or handle it differently based on the new structure

  return df_nested_list

def get_all_news(api_calls_left = 5, api_key = POLYGON_API_KEY, news_limit=1000, max_date = now):
  all_news = None
  for i in range(api_calls_left):
    cur = get_one_chunk_of_news_polygon_io(api_key = api_key, news_limit = news_limit, max_date = max_date)
    if all_news is None:
      all_news = cur
    else:
      all_news = pd.concat([all_news,cur], ignore_index=True, axis=0) #stacking dataframes

    max_date = cur.published_utc.min() #update max_date of the news
  return all_news

64

In [5]:
# test getting all news
# 5 calls per minute limit for a free account - all recent news (5000)
all_news = get_all_news()

trying the API call : https://api.massive.com/v2/reference/news?order=desc&limit=1000&sort=published_utc&published_utc.lt=2026-06-07&apiKey=<your key>
trying the API call : https://api.massive.com/v2/reference/news?order=desc&limit=1000&sort=published_utc&published_utc.lt=2026-06-02T10:55:00Z&apiKey=<your key>
trying the API call : https://api.massive.com/v2/reference/news?order=desc&limit=1000&sort=published_utc&published_utc.lt=2026-05-27T23:43:00Z&apiKey=<your key>
trying the API call : https://api.massive.com/v2/reference/news?order=desc&limit=1000&sort=published_utc&published_utc.lt=2026-05-22T00:07:31Z&apiKey=<your key>
trying the API call : https://api.massive.com/v2/reference/news?order=desc&limit=1000&sort=published_utc&published_utc.lt=2026-05-17T14:52:00Z&apiKey=<your key>

In [6]:
all_news.head()

,id,title,author,published_utc,article_url,tickers,image_url,description,keywords,insights,publisher.name,publisher.homepage_url,publisher.logo_url,publisher.favicon_url,amp_url
0,2688eca3ee024d303668fff82fb03633f2c4b1048e3c91...,3 Cryptocurrencies to Buy Before They Explode,Alex Carchidi,2026-06-06T23:23:00Z,https://www.fool.com/investing/2026/06/06/3-cr...,"[GTAO, ZCSH, PURR]",https://g.foolcdn.com/image/?url=https%3A%2F%2...,The article highlights three cryptocurrencies ...,"[cryptocurrency, tokenomics, decentralized fin...","[{'ticker': 'GTAO', 'sentiment': 'positive', '...",The Motley Fool,https://www.fool.com/,https://s3.massive.com/public/assets/news/logo...,https://s3.massive.com/public/assets/news/favi...,NaN
1,6fcc034255c8a7eaf34efb983d65d7149b8625c4a07732...,Does Palantir's Valuation Make It Too Dangerou...,Keithen Drury,2026-06-06T23:04:00Z,https://www.fool.com/investing/2026/06/06/does...,[PLTR],https://g.foolcdn.com/image/?url=https%3A%2F%2...,Palantir Technologies has seen its stock decli...,"[AI analytics, valuation risk, profit margins,...","[{'ticker': 'PLTR', 'sentiment': 'negative', '...",The Motley Fool,https://www.fool.com/,https://s3.massive.com/public/assets/news/logo...,https://s3.massive.com/public/assets/news/favi...,NaN
2,acd17fe35ea8683d8f231efed098d4de296bf845a4c182...,Could Nvidia Reach a $10 Trillion Market Cap? ...,Keithen Drury,2026-06-06T23:01:00Z,https://www.fool.com/investing/2026/06/06/coul...,"[NVDA, AAPL, AMZN, GOOG, GOOGL]",https://g.foolcdn.com/image/?url=https%3A%2F%2...,Nvidia could reach a $10 trillion market cap w...,"[Nvidia, market cap, GPUs, AI hyperscalers, ca...","[{'ticker': 'NVDA', 'sentiment': 'positive', '...",The Motley Fool,https://www.fool.com/,https://s3.massive.com/public/assets/news/logo...,https://s3.massive.com/public/assets/news/favi...,NaN
3,9d4f0b69d1c49a84bd8ad863174cc5230f93a487a2f9fc...,"ROSEN, A LEADING INVESTOR RIGHTS LAW FIRM, Enc...",Rosen Law Firm,2026-06-06T22:19:00Z,https://www.globenewswire.com/news-release/202...,"[BMI, FSK, FUTU]",https://ml.globenewswire.com/Resource/Download...,Rosen Law Firm has filed class action lawsuits...,"[class action lawsuit, securities fraud, inves...","[{'ticker': 'BMI', 'sentiment': 'negative', 's...",GlobeNewswire Inc.,https://www.globenewswire.com,https://s3.massive.com/public/assets/news/logo...,https://s3.massive.com/public/assets/news/favi...,NaN
4,f3c3dfab9663edc1d3d36dcff4e491a50bffa8addf7dde...,Communiqué Orange : Orange signe un accord pou...,Orange,2026-06-06T22:11:00Z,https://www.globenewswire.com/news-release/202...,"[ORANY, BOUYY]",https://ml-eu.globenewswire.com/Resource/Downl...,"Orange, Bouygues Telecom, and Free-iliad Group...","[SFR acquisition, consortium, telecommunicatio...","[{'ticker': 'ORANY', 'sentiment': 'positive', ...",GlobeNewswire Inc.,https://www.globenewswire.com,https://s3.massive.com/public/assets/news/logo...,https://s3.massive.com/public/assets/news/favi...,NaN

In [7]:
all_news_json = all_news.to_dict(orient='records')

In [8]:
len(all_news_json)

5000

In [9]:
# Key features:

#   1. No chunking needed - Each news article is already a discrete document
#   2. Text search - Searches across title, description, keywords, author
#   3. Exact ticker matching - Function to find articles with specific ticker in tickers field
#   4. Multi-ticker support - Search for multiple tickers at once
#   5. Date filtering - Can filter news by publication date
#   6. Boosting - Title matches get higher priority than description

#   Note on chunking:
#   Unlike the podcast data (long markdown documents), news articles are already atomic units. Each article is a complete piece of information, so no chunking is
#   needed. The tickers field already provides precise ticker associations.

In [10]:

# Import minsearch
from minsearch import Index

# Step 1: Convert DataFrame to list of dicts (if not already done)
news_documents = all_news.to_dict(orient='records')

print(f"Total news articles: {len(news_documents)}")
print(f"Fields per article: {len(news_documents[0])}")
print(f"Sample article keys: {list(news_documents[0].keys())}")

Total news articles: 5000
Fields per article: 15
Sample article keys: ['id', 'title', 'author', 'published_utc', 'article_url', 'tickers', 'image_url', 'description', 'keywords', 'insights', 'publisher.name', 'publisher.homepage_url', 'publisher.logo_url', 'publisher.favicon_url', 'amp_url']

In [11]:
from tqdm import tqdm
  # Step 2: Preprocess documents - convert list fields to strings
print("\nPreprocessing documents...")
for doc in tqdm(news_documents, desc="Converting fields"):
    # Convert list fields to comma-separated strings
    if isinstance(doc.get('tickers'), list):
        doc['tickers'] = ', '.join(doc['tickers'])

    if isinstance(doc.get('keywords'), list):
        doc['keywords'] = ', '.join(doc['keywords'])

    # Ensure text fields are strings
    for field in ['title', 'description', 'author']:
        if doc.get(field) is None:
            doc[field] = ''
        elif not isinstance(doc.get(field), str):
            doc[field] = str(doc[field])

print("✓ Preprocessing complete")

Preprocessing documents...

Converting fields: 100%|██████████| 5000/5000 [00:00<00:00, 771721.07it/s]

✓ Preprocessing complete

In [12]:

  # Step 3: Create Index with relevant text fields
news_index = Index(
    text_fields=["title", "description", "keywords", "author", "tickers"],
    keyword_fields=["published_utc", "publisher.name"]
)

# Step 4: Fit the index with preprocessed documents
print("\nBuilding search index...")
news_index.fit(news_documents)
print(f"✓ Index created with {len(news_documents)} articles")

Building search index...
✓ Index created with 5000 articles

In [13]:
# Step 5: Search function to retrieve news for a ticker
def search_news_by_ticker(ticker, num_results=30):
    """
      Search for news articles related to a specific ticker.
      
      Args:
          ticker: Stock ticker symbol (e.g., 'TSLA', 'AAPL')
          num_results: Number of results to return
      
      Returns:
          List of news articles matching the ticker
    """
    results = news_index.search(
        query=ticker,
        num_results=num_results,
        boost_dict={
              'tickers': 5.0,      # Highest boost for ticker field
              'title': 3.0,         # High boost for title
              'description': 1.5,   # Medium boost for description
              'keywords': 1.0       # Standard boost for keywords
          }
      )
    return results

In [14]:
# Step 6: Search function to retrieve news for a search query
def search_news_by_query(query, num_results=30):
    """
      Search for news articles related to a specific query.
      
      Args:
          query: Search query (e.g., 'Tesla', 'AI robotics')
          num_results: Number of results to return
      
      Returns:
          List of news articles matching the ticker
    """
    results = news_index.search(
        query=query,
        num_results=num_results,
        boost_dict={
              'tickers': 1.0,      # boost for ticker field
              'title': 3.0,         # High boost for title
              'description': 5,   # Highest boost for description
              'keywords': 5       # Highest boost for keywords
          }
      )
    return results

In [15]:

# Step 7: Test - Get news for TSLA
print("\n" + "="*70)
print("Testing search for TSLA...")
print("="*70)

tsla_news = search_news_by_ticker("TSLA", num_results=5)

print(f"\nFound {len(tsla_news)} news articles for TSLA:\n")
for i, article in enumerate(tsla_news, 1):
    print(f"{i}. {article['title']}")
    print(f"   Published: {article['published_utc']}")
    print(f"   Tickers: {article['tickers']}")
    print(f"   Description: {article['description'][:100]}...")
    print()

======================================================================
Testing search for TSLA...
======================================================================

Found 5 news articles for TSLA:

1. Stock Market: Will S&P 500 Open Up Or Down Today?
   Published: 2026-05-22T08:43:59Z
   Tickers: TSLA
   Description: The S&P 500 rose 0.17% on Thursday as easing oil prices and cooling Treasury yields offset inflation...

2. Here's When Tesla's Robotaxi Rollout Will Really Ramp Up
   Published: 2026-05-14T12:05:00Z
   Tickers: TSLA
   Description: Tesla is aggressively expanding its robotaxi fleet, currently operating 39 unsupervised robotaxis ac...

3. Tesla Investors Finally Get A Benchmark For The Musk Premium
   Published: 2026-06-01T17:19:11Z
   Tickers: TSLA
   Description: SpaceX's anticipated IPO will provide investors with a second publicly traded Musk-led company, allo...

4. Governor Kathy Hochul Plans Two-Phase Tax Hike On NYC Luxury Second Homes To Help Plug Budget Shortfall: Report
   Published: 2026-05-15T08:37:00Z
   Tickers: TSLA
   Description: Governor Kathy Hochul proposes a two-phase tax on NYC luxury second homes to raise approximately $50...

5. SpaceX IPO Filing Lands: First Look Inside Elon Musk's Public Offering
   Published: 2026-05-20T21:39:14Z
   Tickers: TSLA
   Description: SpaceX filed for its long-awaited IPO on Wednesday, aiming to raise $75 billion at a $1.75 trillion ...

In [16]:
# Step 8: search news by query
print("\n" + "="*70)
print("Testing search by query...")
print("="*70)

query = "Tesla competitors analysis EV margins autonomy AI robotics China market share outlook"
tsla_competitors_news = search_news_by_query(query, num_results=25)

print(f"\nFound {len(tsla_competitors_news)} news articles for TSLA competitors:\n")
for i, article in enumerate(tsla_competitors_news, 1):
    print(f"{i}. {article['title']}")
    print(f"   Published: {article['published_utc']}")
    print(f"   Tickers: {article['tickers']}")
    print(f"   Description: {article['description'][:100]}...")
    print()

======================================================================
Testing search by query...
======================================================================

Found 25 news articles for TSLA competitors:

1. Elon Musk's Tesla Launches Affordable Financing Plan After Dropping Out Of China's Top EV 10 Makers
   Published: 2026-05-13T09:51:48Z
   Tickers: TSLA, BYDDY, GELHY, ZGJLY, XIACF
   Description: Tesla has dropped out of China's top 10 EV makers as its April retail sales fell to 25,956 units, do...

2. EV Sales Skyrocket: Tesla Stock Surges On 67% European Boom, Blockbuster SpaceX IPO Rumors
   Published: 2026-05-27T15:40:06Z
   Tickers: TSLA, BYDDY, GELHY
   Description: Tesla stock gained 1.11% on Wednesday, driven by strong European EV sales growth (67.2% year-over-ye...

3. Following Trump-Xi Talks, Elon Musk's Tesla Launches Full Self-Driving In China After Years Of Uncertainty
   Published: 2026-05-21T10:26:10Z
   Tickers: TSLA, BYDDY, BA, BApA
   Description: Tesla has launched its Full Self-Driving (FSD) service in China, expanding to 10 countries total, fo...

4. Rivian's Robotics Company Is Now Worth More Than $3 Billion. Investors Could Benefit in 2 Important Ways.
   Published: 2026-05-18T19:15:00Z
   Tickers: RIVN, TSLA
   Description: Rivian's robotics spinoff, Mind Robotics, has reached a $3.4 billion valuation after raising $400 mi...

5. Tesla’s European Recovery Is Real, But BYD Defines the Limit
   Published: 2026-05-27T07:07:00Z
   Tickers: TSLA, BYDDY
   Description: Tesla shows genuine recovery in European EV registrations with three consecutive months of year-on-y...

6. Why Tesla Robotaxi Dreams Can’t Rescue Today’s Weak Fundamentals
   Published: 2026-05-28T12:36:00Z
   Tickers: TSLA, F, FpB, FpC, FpD, GM, BIDU, NIO, LI, XPEV, BYDDY
   Description: Tesla's valuation of $1.3 trillion is heavily dependent on unproven robotaxi and AI technologies, wi...

7. Is China's EV Boom Losing Steam? Tesla Rival Nio's CEO Sounds The Alarm
   Published: 2026-05-28T12:03:08Z
   Tickers: NIO, TSLA, BYDDY
   Description: Nio CEO William Li warns that China's automotive sector has passed its 'golden era,' with domestic c...

8. Should Investors Sell Tesla Stock to Buy SpaceX?
   Published: 2026-06-06T18:05:00Z
   Tickers: TSLA, GM
   Description: A potential SpaceX IPO could fundamentally reshape how investors value Tesla stock. For years, Tesla...

9. BYD Leads China's Global EV Push As Overseas Demand Accelerates
   Published: 2026-06-05T08:08:38Z
   Tickers: BYDDY, CRAUY, GWLLY
   Description: Chinese EV makers BYD and Chery are rapidly expanding overseas sales, with both reporting 81% year-o...

10. Mr. Roboto: Tap Into the Humanoid Robotics Boom With This ETF
   Published: 2026-06-03T13:12:00Z
   Tickers: KOID
   Description: The KraneShares Global Humanoid Robotics and Physical AI Index ETF (KOID) is positioned as a key inv...

11. Tesla: How Bad Could Cybertruck Recall Be for Its Shares?
   Published: 2026-05-13T14:34:00Z
   Tickers: TSLA
   Description: Tesla issued a recall affecting fewer than 200 Cybertrucks due to potential wheel stud cracking risk...

12. 2 Monster EV Stocks Chasing a $10 Trillion AI Opportunity
   Published: 2026-05-29T09:30:00Z
   Tickers: TSLA, RIVN, UBER
   Description: The article highlights how EV companies are positioned to capitalize on a $10 trillion robotaxi mark...

13. Elon Musk Just Linked SpaceX, xAI, Tesla, and Nvidia Into 1 Trade. Here's How to Position Your Portfolio.
   Published: 2026-05-23T18:14:00Z
   Tickers: TSLA, NVDA
   Description: The article analyzes how Elon Musk's companies—SpaceX, xAI, Tesla, and Nvidia—form an integrated AI ...

14. How Nio Is Proving It's a Top Auto Stock Despite Brutal the Price War
   Published: 2026-06-03T17:07:00Z
   Tickers: NIO, BYDDY, GELHY
   Description: Nio is outperforming competitors in China's brutal EV price war, posting 62% delivery growth in May ...

15. Auditoria.AI introduces Governed Autonomy for Enterprise Office of the CFO at 2026 Gartner CFO Symposium
   Published: 2026-05-26T12:00:00Z
   Tickers: WDAY, ORCL, ORCLpD, SAP, NOW, MSFT
   Description: Auditoria.AI unveiled Governed Autonomy, a new operating framework that enables autonomous AI agents...

16. Is Tesla Stock Your Ticket to Becoming a Millionaire?
   Published: 2026-05-31T08:34:00Z
   Tickers: TSLA
   Description: While Tesla's stock has delivered exceptional historical returns (22,250% over 15 years), the articl...

17. 'Trump And Republicans Blew That Up:' Gavin Newsom Warns America Is Losing EV War To China
   Published: 2026-05-13T04:22:43Z
   Tickers: TSLA, AAPL, BA, BApA, NVDA
   Description: California Governor Gavin Newsom criticized President Trump and Republicans for slowing America's EV...

18. Softbank's Masayoshi Son Isn't Worried About An AI Bubble— He's Hunting For The Next Trillion-Dollar Industry: 'Just The Beginning'
   Published: 2026-06-02T08:46:39Z
   Tickers: SFTBY, ABBNY, META, GS, GSpA, GSpC, GSpD, AMJB, JPM, JPMpC, JPMpD, JPMpJ, JPMpK, JPMpL, JPMpM, VYLD, MS, MSpA, MSpE, MSpF, MSpI, MSpK, MSpL, MSpO, MSpP, MSpQ
   Description: SoftBank CEO Masayoshi Son believes the AI revolution is '50x bigger' than the dot-com boom and will...

19. Tesla Just Hiked Model Y Prices for the First Time Since 2024. Time to Buy the Stock?
   Published: 2026-05-18T22:13:00Z
   Tickers: TSLA
   Description: Tesla raised Model Y prices for the first time in about two years, with Premium trims increasing by ...

20. Where Will Tesla Stock Be in 3 Years?
   Published: 2026-06-05T03:22:00Z
   Tickers: TSLA
   Description: Tesla's business is stabilizing with recovered profit margins and strong Chinese sales growth, while...

21. This EV Stock Could Soar By 79%, According to a Wall Street Analyst (Hint: Not Tesla)
   Published: 2026-05-19T09:30:00Z
   Tickers: RIVN, TSLA, UBER
   Description: Rivian Automotive has a $25 price target from Benchmark Company analyst Mickey Legg, implying 79% up...

22. China's Puncture Robotics Firm True Health Files For Hong Kong IPO
   Published: 2026-06-05T12:55:58Z
   Tickers: ISRG
   Description: Guangdong true Health Medical Technology, a Chinese medical robotics company specializing in punctur...

23. Nio Is Zigging While Rivals Zag, and Shockingly It's Winning
   Published: 2026-06-06T07:05:00Z
   Tickers: NIO, BYDDY, GELHY
   Description: While Chinese automakers like BYD and Geely are rushing to export vehicles overseas to offset declin...

24. Tesla Investors Beware? SpaceX IPO Could Pull Cash, Attention And Musk Away From EV Giant
   Published: 2026-05-22T05:39:55Z
   Tickers: TSLA
   Description: SpaceX's upcoming IPO could negatively impact Tesla as it may divert investor attention, capital, an...

25. Here's Why Tesla Stock Is a Buy Before 2031
   Published: 2026-05-13T08:05:00Z
   Tickers: TSLA
   Description: Tesla stock has surged 30% over the past month as the company pivots from declining auto sales to th...

# 2) TEST: Checking Yahoo Finance API endpoints

In [17]:
# https://github.com/ranaroussi/yfinance
# https://algotrading101.com/learn/yfinance-guide/

import yfinance as yf
ticker="TSLA"
ticker_obj = yf.Ticker(ticker)

In [18]:
# daily stats for a stock: Open, High, Low, Close, Volume
historical_prices = ticker_obj.history(period="2y", interval="1d")

# show only date part in the index
historical_prices.index = historical_prices.index.date

historical_prices.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
2024-06-06,174.600006,179.729996,172.729996,177.940002,69887000,0.0,0.0
2024-06-07,176.130005,179.350006,175.580002,177.479996,56244900,0.0,0.0
2024-06-10,176.059998,178.570007,173.169998,173.789993,50774600,0.0,0.0
2024-06-11,173.919998,174.750000,167.410004,170.660004,64761900,0.0,0.0
2024-06-12,171.119995,180.550003,169.800003,177.289993,90389400,0.0,0.0

In [19]:
# Analyst price targets
ticker_obj.get_analyst_price_targets()

{'current': 391.0,
 'high': 600.0,
 'low': 123.0,
 'mean': 419.93658,
 'median': 460.0}

In [20]:
# Dividends or Stock splits history
ticker_obj.actions

                           Dividends  Stock Splits
Date
2020-08-31 00:00:00-04:00        0.0           5.0
2022-08-25 00:00:00-04:00        0.0           3.0

In [21]:
# Next earnings date + targets on EPS (Earnings)/revenue
ticker_obj.calendar

{'Earnings Date': [datetime.date(2026, 7, 22)],
 'Earnings High': 0.59,
 'Earnings Low': 0.26483,
 'Earnings Average': 0.45432,
 'Revenue High': 26059000000,
 'Revenue Low': 22543000000,
 'Revenue Average': 24625317630}

In [22]:
# FIN STATEMENTS -- too much of info, not needed for now
# ticker_obj.get_balancesheet()
# ticker_obj.get_cash_flow()
# ticker_obj.get_income_stmt()
# same as income stmt: ticker_obj.get_financials()

In [23]:
# EPS estimates vs. numberOfAnalysts
ticker_obj.get_earnings_estimate()

            avg      low  high  yearAgoEps  numberOfAnalysts  growth
period
0q      0.45432  0.26483  0.59     0.40000                24  0.1358
+1q     0.54031  0.29981  0.83     0.50000                24  0.0806
0y      2.04967  1.35491  3.19     1.66000                34  0.2347
+1y     2.50462  1.46400  3.65     2.04967                30  0.2220

In [24]:
# How analysts have revised their EPS estimates over time?
ticker_obj.get_eps_revisions()

        upLast7days  upLast30days  downLast30days  downLast7Days
period
0q                9             7              14             10
+1q               7             5              13             10
0y               14             7              18             11
+1y               7             3              19             15

In [25]:
# This section retrieves consensus analyst growth expectations from Yahoo Finance for the selected ticker. 
# The values represent estimated earnings growth and are expressed in decimal form, 
# where positive values indicate expected growth and negative values indicate contraction. 
# Estimates are provided across multiple time horizons: 0q refers to the current fiscal quarter, 
# +1q to the next fiscal quarter, 0y to the current fiscal year, and +1y to the next fiscal year.
#  Short-term quarterly estimates tend to be more volatile, while annual estimates provide a broader view of expected performance.

ticker_obj.get_growth_estimates()

        stockTrend  indexTrend
period
0q          0.1358      0.2598
+1q         0.0806      0.2026
0y          0.2347      0.2290
+1y         0.2220      0.1669
LTG            NaN      0.1220

In [26]:
ticker_obj.get_earnings_history()

            epsActual  epsEstimate  epsDifference  surprisePercent
quarter
2025-06-30       0.40      0.40391         -0.004          -0.0097
2025-09-30       0.50      0.55885         -0.060          -0.1053
2025-12-31       0.50      0.45061          0.050           0.1096
2026-03-31       0.41      0.34999          0.060           0.1715

In [27]:
import pandas as pd
news = pd.DataFrame(ticker_obj.get_news())
news.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       10 non-null     object
 1   content  10 non-null     object
dtypes: object(2)
memory usage: 292.0+ bytes

In [28]:
news

,id,content
0,d03c9964-5f71-3f59-9eb7-e50366ffcca3,"{'id': 'd03c9964-5f71-3f59-9eb7-e50366ffcca3',..."
1,02d6b98f-0607-316d-86c6-7b50ee76b383,"{'id': '02d6b98f-0607-316d-86c6-7b50ee76b383',..."
2,a22249e0-8787-3c62-9831-fe23f9e329e2,"{'id': 'a22249e0-8787-3c62-9831-fe23f9e329e2',..."
3,4a0f39f8-f230-3ae6-8272-d5a787940f84,"{'id': '4a0f39f8-f230-3ae6-8272-d5a787940f84',..."
4,9a0a7623-29a9-3520-874e-5416a2c4bdf2,"{'id': '9a0a7623-29a9-3520-874e-5416a2c4bdf2',..."
5,e1e6bef0-e7bc-3983-961e-b88ca886bcde,"{'id': 'e1e6bef0-e7bc-3983-961e-b88ca886bcde',..."
6,fd5a6635-3ef1-33c7-8bbe-7995355702f2,"{'id': 'fd5a6635-3ef1-33c7-8bbe-7995355702f2',..."
7,9243c15c-a4a3-3a5b-9b01-c24867df72bf,"{'id': '9243c15c-a4a3-3a5b-9b01-c24867df72bf',..."
8,25a9b628-37a6-3f6f-96dc-2b689005622f,"{'id': '25a9b628-37a6-3f6f-96dc-2b689005622f',..."
9,47f4038d-cfac-32d5-ae6b-d9d651142564,"{'id': '47f4038d-cfac-32d5-ae6b-d9d651142564',..."

In [29]:
import pandas as pd

# Create a new DataFrame from the 'content' column of the 'news' DataFrame
news_df = pd.DataFrame(news['content'].tolist())

# Display the first few rows of the new DataFrame
display(news_df.head())

,id,contentType,title,description,summary,pubDate,displayTime,isHosted,bypassModal,previewUrl,thumbnail,provider,canonicalUrl,clickThroughUrl,metadata,finance,storyline
0,d03c9964-5f71-3f59-9eb7-e50366ffcca3,STORY,“Wait for the First Dip and Then Come In.” How...,,While much of the market is gearing up to chas...,2026-06-07T12:11:22Z,2026-06-07T12:11:22Z,True,False,None,{'originalUrl': 'https://media.zenfs.com/en/24...,"{'displayName': '24/7 Wall St.', 'url': 'https...",{'url': 'https://247wallst.com/investing/2026/...,{'url': 'https://finance.yahoo.com/markets/sto...,{'editorsPick': False},"{'premiumFinance': {'isPremiumNews': False, 'i...",None
1,02d6b98f-0607-316d-86c6-7b50ee76b383,STORY,Why Growth Investors Should Avoid the SpaceX IPO,,The long-term growth potential of the stock co...,2026-06-07T11:25:00Z,2026-06-07T11:25:00Z,True,False,None,{'originalUrl': 'https://media.zenfs.com/en/mo...,"{'displayName': 'Motley Fool', 'url': 'http://...",{'url': 'https://www.fool.com/investing/2026/0...,{'url': 'https://finance.yahoo.com/markets/sto...,{'editorsPick': False},"{'premiumFinance': {'isPremiumNews': False, 'i...",None
2,a22249e0-8787-3c62-9831-fe23f9e329e2,STORY,Where do Waymo and Tesla currently stand in th...,,Investing.com -- Tesla (NASDAQ: TSLA) is makin...,2026-06-07T07:51:22Z,2026-06-07T07:51:22Z,True,False,None,None,"{'displayName': 'Investing.com', 'url': 'https...",{'url': 'https://finance.yahoo.com/sectors/tec...,{'url': 'https://finance.yahoo.com/sectors/tec...,{'editorsPick': False},"{'premiumFinance': {'isPremiumNews': False, 'i...",None
3,4a0f39f8-f230-3ae6-8272-d5a787940f84,STORY,"The 4 Best ""Magnificent Seven"" Stocks to Buy Now",,"Amazon, Meta Platforms, Microsoft, and Nvidia ...",2026-06-07T03:42:00Z,2026-06-07T03:42:00Z,True,False,None,{'originalUrl': 'https://media.zenfs.com/en/mo...,"{'displayName': 'Motley Fool', 'url': 'http://...",{'url': 'https://www.fool.com/investing/2026/0...,{'url': 'https://finance.yahoo.com/markets/sto...,{'editorsPick': False},"{'premiumFinance': {'isPremiumNews': False, 'i...",None
4,9a0a7623-29a9-3520-874e-5416a2c4bdf2,STORY,Meet the AI Company That Can Thrive Even if an...,,Tesla is integrating artificial intelligence (...,2026-06-07T02:20:00Z,2026-06-07T02:20:00Z,True,False,None,{'originalUrl': 'https://media.zenfs.com/en/mo...,"{'displayName': 'Motley Fool', 'url': 'http://...",{'url': 'https://www.fool.com/investing/2026/0...,{'url': 'https://finance.yahoo.com/markets/sto...,{'editorsPick': False},"{'premiumFinance': {'isPremiumNews': False, 'i...",None

In [30]:
# summary of news articles for the ticker (Yahoo Finance)
from pprint import pprint 
for e in news_df.summary:
    pprint(e)
    print('-----')

('While much of the market is gearing up to chase the SpaceX listing on day '
 'one, Constellation Research Chairman Ray Wang appeared on CNBC’s Squawk Box '
 'this morning, June 5, with a different message for retail investors: “I '
 'would actually wait for the IPO and wait for the first dip and then come '
 'in,” Wang ... “Wait for the First Dip and Then Come In.” How Wall Street '
 'Experts Are Playing the SpaceX IPO.')
-----
("The long-term growth potential of the stock compares poorly to Elon Musk's "
 'other company, Tesla, for one key reason.')
-----
('Investing.com -- Tesla (NASDAQ: TSLA) is making progress in autonomous '
 'driving, but Waymo remains the clear leader in commercial robotaxi '
 'operations, according to a Barclays research note.')
-----
'Amazon, Meta Platforms, Microsoft, and Nvidia look underpriced.'
-----
('Tesla is integrating artificial intelligence (AI) into its solutions rather '
 'than relying on it to drive revenue growth. That could be good news over the '
 'long term if the AI bubble bursts.')
-----
('Tesla Robotaxi has been on a long road, and after surpassing 1.7 million '
 'paid miles traveled earlier this year, Tesla sees a much smoother road ahead '
 'for its tentpole technology. Tesla bulls point to autonomous driving '
 "technology as the missing piece that will unlock the company's true "
 'valuation. ...')
-----
('Tesla China sales jumped almost 40% in May as its FSD software rolled out '
 "globally. Here's why TSLA stock still belongs on your watch list now.")
-----
"A SpaceX IPO could fundamentally change how investors perceive Tesla's stock."
-----
('SpaceX and Tesla Inc. CEO Elon Musk on Wednesday said the EV giant’s Terafab '
 'chip fabrication facility in Grimes County, Texas, would become the county’s '
 'largest source of revenue. Terafab To Account For 25% Tax Revenue In a '
 'response to...')
-----
('There were some clunkers and expected early stumbles. By and large, though, '
 'most have done pretty well.')
-----

In [31]:
# Fast info about the stock
ticker_obj.get_fast_info().items()

[('currency', 'USD'),
 ('dayHigh', 424.67999267578125),
 ('dayLow', 388.5899963378906),
 ('exchange', 'NMS'),
 ('fiftyDayAverage', 395.2886010742188),
 ('lastPrice', 391.0),
 ('lastVolume', 63128800),
 ('marketCap', 1468488033561.0),
 ('open', 420.5),
 ('previousClose', 416.19),
 ('quoteType', 'EQUITY'),
 ('regularMarketPreviousClose', 418.45001220703125),
 ('shares', 3755723871),
 ('tenDayAverageVolume', 43951860),
 ('threeMonthAverageVolume', 59657679),
 ('timezone', 'America/New_York'),
 ('twoHundredDayAverage', 414.1418504333496),
 ('yearChange', 0.2670944876991646),
 ('yearHigh', 498.8299865722656),
 ('yearLow', 281.8500061035156)]

In [32]:
import json

In [33]:
# a lot of info - potentially useful fields:
# website, industry, sector, fullTimeEmployees, companyOfficers, previousClose, open, dayLow, dayHigh, 
# beta, forwardPE, trailingPE, volume, averageVolume, averageVolume10days, marketCap, fiftyTwoWeekLow, 
# fiftyTwoWeekHigh, allTimeHigh, allTimeLow, priceToSalesTrailing12Months, fiftyDayAverage, twoHundredDayAverage
# profitMargins, sharesPercentSharesOut, heldPercentInsiders, heldPercentInstitutions, shortRatio, bookValue, priceToBook
# earningsQuarterlyGrowth, trailingEps, forwardEps, 52WeekChange, currentPrice,
#   targetHighPrice, targetLowPrice, targetMeanPrice, targetMedianPrice, recommendationMean,
# recommendationKey, numberOfAnalystOpinions, totalCashPerShare,totalCashPerShare, returnOnAssets, returnOnEquity,
# earningsGrowth, revenueGrowth, grossMargins, ebitdaMargins, operatingMargins, region, fullExchangeName, regularMarketDayRange, fiftyTwoWeekRange,
# fiftyTwoWeekHighChange, cryptoTradeable, displayName, trailingPegRatio
info = ticker_obj.get_info()
print(json.dumps(info, indent=2, default=str))

{
  "address1": "1 Tesla Road",
  "city": "Austin",
  "state": "TX",
  "zip": "78725",
  "country": "United States",
  "phone": "512 516 8177",
  "website": "https://www.tesla.com",
  "industry": "Auto Manufacturers",
  "industryKey": "auto-manufacturers",
  "industryDisp": "Auto Manufacturers",
  "sector": "Consumer Cyclical",
  "sectorKey": "consumer-cyclical",
  "sectorDisp": "Consumer Cyclical",
  "longBusinessSummary": "Tesla, Inc. designs, develops, manufactures, leases, and sells electric vehicles, and energy generation and storage systems in the United States, China, and internationally. The company operates in two segments, Automotive; and Energy Generation and Storage. The company offers electric vehicles, as well as sells automotive regulatory credits; and non-warranty maintenance services and collision, automotive insurance services, as well as part sales and retail merchandise sale. It also provides sedans and sport utility vehicles through direct and used vehicle sales, a network of Tesla Superchargers, and in-app upgrades; purchase financing and leasing services; services for electric vehicles through its company-owned service locations and Tesla mobile service technicians; and vehicle limited warranties and extended service plans. In addition, the company engages in the design, manufacture, installation, sale, and leasing of solar energy generation and energy storage products, and related services to residential, commercial, and industrial customers and utilities through its website, stores, and galleries, as well as through a network of channel partners. Further, it provides services and repairs to its energy product customers, including under warranty and extended service plans; and various financing options to its residential customers; lithium-ion battery energy storage products, such as Powerwall and Megapack; energy generation products, including solar panels and solar roof; self-driving development and artificial intelligence software, vehicle control and infotainment software, and battery and powertrain. The company was formerly known as Tesla Motors, Inc. and changed its name to Tesla, Inc. in February 2017. Tesla, Inc. was incorporated in 2003 and is headquartered in Austin, Texas.",
  "fullTimeEmployees": 134785,
  "companyOfficers": [
    {
      "maxAge": 1,
      "name": "Mr. Elon R. Musk",
      "age": 54,
      "title": "Co-Founder, Technoking of Tesla, CEO & Director",
      "yearBorn": 1971,
      "fiscalYear": 2025,
      "exercisedValue": 0,
      "unexercisedValue": 129602732032
    },
    {
      "maxAge": 1,
      "name": "Mr. Vaibhav  Taneja",
      "age": 47,
      "title": "Chief Financial Officer",
      "yearBorn": 1978,
      "fiscalYear": 2025,
      "totalPay": 403000,
      "exercisedValue": 15033838,
      "unexercisedValue": 417696224
    },
    {
      "maxAge": 1,
      "name": "Mr. Xiaotong  Zhu",
      "age": 45,
      "title": "Senior Vice President of APAC & Global Vehicle Manufacturing",
      "yearBorn": 1980,
      "fiscalYear": 2025,
      "totalPay": 376322,
      "exercisedValue": 4548562,
      "unexercisedValue": 808327104
    },
    {
      "maxAge": 1,
      "name": "Travis  Axelrod",
      "title": "Head of Investor Relations",
      "fiscalYear": 2025,
      "exercisedValue": 0,
      "unexercisedValue": 0
    },
    {
      "maxAge": 1,
      "name": "Mr. Brandon  Ehrhart",
      "title": "General Counsel & Corporate Secretary",
      "fiscalYear": 2025,
      "exercisedValue": 0,
      "unexercisedValue": 0
    },
    {
      "maxAge": 1,
      "name": "Mr. Franz  von Holzhausen",
      "title": "Chief Designer",
      "fiscalYear": 2025,
      "exercisedValue": 0,
      "unexercisedValue": 0
    },
    {
      "maxAge": 1,
      "name": "Ms. Roxanne  Inskip-Kaye",
      "title": "Head of Operations - Electric Vehicle Business",
      "fiscalYear": 2025,
      "exercisedValue": 0,
      "unexercisedValue": 0
    },
    {
      "maxAge": 1,
      "name": "Mr. John  Walker",
      "age": 62,
      "title": "Vice President of Sales - North America",
      "yearBorn": 1963,
      "fiscalYear": 2025,
      "totalPay": 121550,
      "exercisedValue": 0,
      "unexercisedValue": 0
    },
    {
      "maxAge": 1,
      "name": "Mr. Rodney D. Westmoreland Jr.",
      "title": "Director of Construction Management",
      "fiscalYear": 2025,
      "exercisedValue": 0,
      "unexercisedValue": 0
    },
    {
      "maxAge": 1,
      "name": "Mr. Lars  Moravy",
      "title": "Vice President of Vehicle Engineering",
      "fiscalYear": 2025,
      "exercisedValue": 0,
      "unexercisedValue": 0
    }
  ],
  "auditRisk": 4,
  "boardRisk": 10,
  "compensationRisk": 10,
  "shareHolderRightsRisk": 9,
  "overallRisk": 10,
  "governanceEpochDate": 1780531200,
  "compensationAsOfEpochDate": 1767139200,
  "executiveTeam": [],
  "maxAge": 86400,
  "priceHint": 2,
  "previousClose": 418.45,
  "open": 420.545,
  "dayLow": 388.59,
  "dayHigh": 424.6799,
  "regularMarketPreviousClose": 418.45,
  "regularMarketOpen": 420.545,
  "regularMarketDayLow": 388.59,
  "regularMarketDayHigh": 424.6799,
  "payoutRatio": 0.0,
  "beta": 1.798,
  "trailingPE": 358.71558,
  "forwardPE": 156.1115,
  "volume": 60830180,
  "regularMarketVolume": 60830180,
  "averageVolume": 59863080,
  "averageVolume10days": 42880690,
  "averageDailyVolume10Day": 42880690,
  "bid": 391.52,
  "ask": 391.87,
  "bidSize": 1,
  "askSize": 4,
  "marketCap": 1468487958528,
  "nonDilutedMarketCap": 1591300204142,
  "fiftyTwoWeekLow": 273.21,
  "fiftyTwoWeekHigh": 498.83,
  "allTimeHigh": 498.83,
  "allTimeLow": 0.998667,
  "priceToSalesTrailing12Months": 15.003096,
  "fiftyDayAverage": 394.4792,
  "twoHundredDayAverage": 413.41696,
  "trailingAnnualDividendRate": 0.0,
  "trailingAnnualDividendYield": 0.0,
  "currency": "USD",
  "tradeable": false,
  "enterpriseValue": 1440320978944,
  "profitMargins": 0.03946,
  "floatShares": 2815891530,
  "sharesOutstanding": 3755723871,
  "sharesShort": 75190815,
  "sharesShortPriorMonth": 71106902,
  "sharesShortPreviousMonthDate": 1776211200,
  "dateShortInterest": 1778803200,
  "sharesPercentSharesOut": 0.02,
  "heldPercentInsiders": 0.11111,
  "heldPercentInstitutions": 0.44912997,
  "shortRatio": 1.18,
  "shortPercentOfFloat": 0.0225,
  "impliedSharesOutstanding": 3755723871,
  "bookValue": 21.897,
  "priceToBook": 17.856327,
  "lastFiscalYearEnd": 1767139200,
  "nextFiscalYearEnd": 1798675200,
  "mostRecentQuarter": 1774915200,
  "earningsQuarterlyGrowth": 0.166,
  "netIncomeToCommon": 3862000128,
  "trailingEps": 1.09,
  "forwardEps": 2.50462,
  "pegRatio": 5.38,
  "lastSplitFactor": "3:1",
  "lastSplitDate": 1661385600,
  "enterpriseToRevenue": 14.715,
  "enterpriseToEbitda": 129.829,
  "52WeekChange": 0.4882332,
  "SandP52WeekChange": 0.27181315,
  "quoteType": "EQUITY",
  "currentPrice": 391.0,
  "targetHighPrice": 600.0,
  "targetLowPrice": 123.0,
  "targetMeanPrice": 419.93658,
  "targetMedianPrice": 460.0,
  "recommendationMean": 2.34043,
  "recommendationKey": "buy",
  "numberOfAnalystOpinions": 41,
  "totalCash": 44743000064,
  "totalCashPerShare": 11.913,
  "ebitda": 11093999616,
  "totalDebt": 15889999872,
  "quickRatio": 1.43,
  "currentRatio": 2.043,
  "totalRevenue": 97878999040,
  "debtToEquity": 18.738,
  "revenuePerShare": 30.312,
  "returnOnAssets": 0.022330001,
  "returnOnEquity": 0.04901,
  "grossProfits": 18660999168,
  "freeCashflow": 5251999744,
  "operatingCashflow": 16528000000,
  "earningsGrowth": 0.083,
  "revenueGrowth": 0.158,
  "grossMargins": 0.19065,
  "ebitdaMargins": 0.11334,
  "operatingMargins": 0.04203,
  "financialCurrency": "USD",
  "symbol": "TSLA",
  "language": "en-US",
  "region": "US",
  "typeDisp": "Equity",
  "quoteSourceName": "Nasdaq Real Time Price",
  "triggerable": true,
  "customPriceAlertConfidence": "HIGH",
  "shortName": "Tesla, Inc.",
  "longName": "Tesla, Inc.",
  "averageAnalystRating": "2.3 - Buy",
  "cryptoTradeable": false,
  "marketState": "CLOSED",
  "hasPrePostMarketData": true,
  "firstTradeDateMilliseconds": 1277818200000,
  "postMarketChangePercent": 0.082483314,
  "postMarketPrice": 391.3225,
  "postMarketChange": 0.32250977,
  "regularMarketChange": -27.45,
  "regularMarketDayRange": "388.59 - 424.6799",
  "fullExchangeName": "NasdaqGS",
  "averageDailyVolume3Month": 59863080,
  "fiftyTwoWeekLowChange": 117.79001,
  "fiftyTwoWeekLowChangePercent": 0.4311336,
  "fiftyTwoWeekRange": "273.21 - 498.83",
  "fiftyTwoWeekHighChange": -107.82999,
  "fiftyTwoWeekHighChangePercent": -0.21616581,
  "fiftyTwoWeekChangePercent": 48.823322,
  "earningsTimestamp": 1776888000,
  "earningsTimestampStart": 1784750400,
  "earningsTimestampEnd": 1784750400,
  "earningsCallTimestampStart": 1776893400,
  "earningsCallTimestampEnd": 1776893400,
  "isEarningsDateEstimate": true,
  "epsTrailingTwelveMonths": 1.09,
  "epsForward": 2.50462,
  "epsCurrentYear": 2.04967,
  "priceEpsCurrentYear": 190.76242,
  "fiftyDayAverageChange": -3.479187,
  "fiftyDayAverageChangePercent": -0.008819697,
  "twoHundredDayAverageChange": -22.416962,
  "twoHundredDayAverageChangePercent": -0.054223612,
  "sourceInterval": 15,
  "exchangeDataDelayedBy": 0,
  "regularMarketChangePercent": -6.55993,
  "regularMarketPrice": 391.0,
  "corporateActions": [],
  "postMarketTime": 1780703999,
  "regularMarketTime": 1780689600,
  "exchange": "NMS",
  "messageBoardId": "finmb_27444752",
  "exchangeTimezoneName": "America/New_York",
  "exchangeTimezoneShortName": "EDT",
  "gmtOffSetMilliseconds": -14400000,
  "market": "us_market",
  "esgPopulated": false,
  "displayName": "Tesla",
  "trailingPegRatio": 5.7618
}

In [34]:
# more history metadata - not sure we need this now
import json

metadata = ticker_obj.get_history_metadata()
print(json.dumps(metadata, indent=2, default=str))

{
  "currency": "USD",
  "symbol": "TSLA",
  "exchangeName": "NMS",
  "fullExchangeName": "NasdaqGS",
  "instrumentType": "EQUITY",
  "firstTradeDate": 1277818200,
  "regularMarketTime": 1780689600,
  "hasPrePostMarketData": true,
  "gmtoffset": -14400,
  "timezone": "EDT",
  "exchangeTimezoneName": "America/New_York",
  "regularMarketPrice": 391.0,
  "fiftyTwoWeekHigh": 498.83,
  "fiftyTwoWeekLow": 273.21,
  "regularMarketDayHigh": 424.68,
  "regularMarketDayLow": 388.59,
  "regularMarketVolume": 60830180,
  "longName": "Tesla, Inc.",
  "shortName": "Tesla, Inc.",
  "chartPreviousClose": 435.79,
  "previousClose": 418.45,
  "scale": 3,
  "priceHint": 2,
  "currentTradingPeriod": {
    "pre": {
      "timezone": "EDT",
      "start": 1780646400,
      "end": 1780666200,
      "gmtoffset": -14400
    },
    "regular": {
      "timezone": "EDT",
      "start": 1780666200,
      "end": 1780689600,
      "gmtoffset": -14400
    },
    "post": {
      "timezone": "EDT",
      "start": 1780689600,
      "end": 1780704000,
      "gmtoffset": -14400
    }
  },
  "tradingPeriods": {
    "pre": [
      [
        {
          "timezone": "EDT",
          "start": 1780300800,
          "end": 1780320600,
          "gmtoffset": -14400
        }
      ],
      [
        {
          "timezone": "EDT",
          "start": 1780387200,
          "end": 1780407000,
          "gmtoffset": -14400
        }
      ],
      [
        {
          "timezone": "EDT",
          "start": 1780473600,
          "end": 1780493400,
          "gmtoffset": -14400
        }
      ],
      [
        {
          "timezone": "EDT",
          "start": 1780560000,
          "end": 1780579800,
          "gmtoffset": -14400
        }
      ],
      [
        {
          "timezone": "EDT",
          "start": 1780646400,
          "end": 1780666200,
          "gmtoffset": -14400
        }
      ]
    ],
    "post": [
      [
        {
          "timezone": "EDT",
          "start": 1780344000,
          "end": 1780358400,
          "gmtoffset": -14400
        }
      ],
      [
        {
          "timezone": "EDT",
          "start": 1780430400,
          "end": 1780444800,
          "gmtoffset": -14400
        }
      ],
      [
        {
          "timezone": "EDT",
          "start": 1780516800,
          "end": 1780531200,
          "gmtoffset": -14400
        }
      ],
      [
        {
          "timezone": "EDT",
          "start": 1780603200,
          "end": 1780617600,
          "gmtoffset": -14400
        }
      ],
      [
        {
          "timezone": "EDT",
          "start": 1780689600,
          "end": 1780704000,
          "gmtoffset": -14400
        }
      ]
    ],
    "regular": [
      [
        {
          "timezone": "EDT",
          "start": 1780320600,
          "end": 1780344000,
          "gmtoffset": -14400
        }
      ],
      [
        {
          "timezone": "EDT",
          "start": 1780407000,
          "end": 1780430400,
          "gmtoffset": -14400
        }
      ],
      [
        {
          "timezone": "EDT",
          "start": 1780493400,
          "end": 1780516800,
          "gmtoffset": -14400
        }
      ],
      [
        {
          "timezone": "EDT",
          "start": 1780579800,
          "end": 1780603200,
          "gmtoffset": -14400
        }
      ],
      [
        {
          "timezone": "EDT",
          "start": 1780666200,
          "end": 1780689600,
          "gmtoffset": -14400
        }
      ]
    ]
  },
  "dataGranularity": "1h",
  "range": "5d",
  "validRanges": [
    "1d",
    "5d",
    "1mo",
    "3mo",
    "6mo",
    "1y",
    "2y",
    "5y",
    "10y",
    "ytd",
    "max"
  ],
  "lastTrade": {
    "Price": 391.3225,
    "Time": "2026-06-05 19:59:59-04:00"
  }
}

## 3) TEST Social posts from X/Reddit
 * https://docs.x.ai/developers/tools/x-search
 * https://docs.x.ai/developers/tools/citations
 * IMPORTANT! We're using the OpenAI's compatible function call (Responses API) rather than what you can read on the x-search page

In [62]:
def get_recent_social_posts(ticker: str, max_posts: int = 5, days_back: int = 1):
    """
    Enhanced version with more x_search parameters.
    """
    
    api_key = os.getenv('XAI_API_KEY')
    if not api_key:
        return {
            'ticker': ticker,
            'error': 'XAI_API_KEY not found',
            'posts': []
        }
    
    try:
        from datetime import datetime, timedelta
        
        client = openai.OpenAI(
            api_key=api_key,
            base_url="https://api.x.ai/v1"
        )
        
        # Calculate date range
        to_date = datetime.now()
        from_date = to_date - timedelta(days=days_back)
        
        # Enhanced search query
        search_query = f"""
        Search X/Twitter for recent posts about ${ticker} stock.
        
        Requirements:
        - Find {max_posts} posts from the last {days_back} day(s)
        - Sort by most recent timestamp first
        - Include exact post times (e.g., "2 hours ago", "45 minutes ago")
        - Provide real, working X.com links
        - Include post content, author handles, engagement metrics
        - Analyze sentiment (bullish/bearish/neutral)
        
        Focus on posts about:
        - Stock price movements
        - Company news reactions
        - Earnings discussions
        - Technical analysis
        - Market sentiment
        
        Date range: {from_date.strftime('%Y-%m-%d')} to {to_date.strftime('%Y-%m-%d')}
        """
        
        response = client.responses.create(
            model="grok-4.3",
            input=search_query,
            tools=[{"type": "x_search"}]
        )
        
        # Extract response content
        content = ""
        for item in response.output:
            if item.type == "message":
                for content_block in item.content:
                    if content_block.type == "output_text":
                        content += content_block.text
        
        return {
            'ticker': ticker,
            'response': content,
            'posts': [],
            'search_params': {
                'max_posts': max_posts,
                'days_back': days_back,
                'date_range': f"{from_date.strftime('%Y-%m-%d')} to {to_date.strftime('%Y-%m-%d')}"
            },
            'timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            'api_used': 'responses_api_with_x_search'
        }
        
    except Exception as e:
        return {
            'ticker': ticker,
            'error': f'Error: {str(e)}',
            'posts': []
        }

In [63]:
# We'll test the news retrieval and search functionality with a specific ticker and a limit on the number of posts to retrieve.
max_posts = 10
ticker = 'TSLA'

# Test it
print("Testing X.AI ...")
result = get_recent_social_posts(ticker, max_posts)
if 'error' in result:
    print(f"❌ {result['error']}")
else:
    print(f"✅ Got response for {result['ticker']}")

Testing X.AI ...
✅ Got response for TSLA

In [64]:
print(result['response'])

**Here are 10 recent X posts about $TSLA stock** (from the date range 2026-06-06 to 2026-06-07), sorted by most recent timestamp first. All posts were retrieved via advanced keyword search for "$TSLA" or "TSLA" in Latest mode.

**Note**: Post volume on deep stock-specific topics (e.g., price movements, earnings, or technical analysis) was limited in this exact window. The results primarily include mentions in trading strategies, portfolios, or indirect discussions. All links are direct to x.com and should work. Times are shown as exact GMT timestamps from the posts (relative "X hours ago" approximated based on ~15:00 GMT current time on 2026-06-07).

1. **@teshen8lin** (El Profesor Garlic)
   **Time**: Sun, 07 Jun 2026 14:11:32 GMT (~1 hour ago)
   **Content**: It’s a calculated plot against Elon Musk’s Terafab 🤔 $INTC $SPCX $TSLA $TSM
   **Engagement**: 0 likes, 0 reposts, 0 replies, 5 views
   **Link**: https://x.com/teshen8lin/status/2063624905283813516
   **Sentiment**: Neutral (conspiracy-tinged mention)

2. **@deplorabletrdr** (Deplorable Trader)
   **Time**: Sun, 07 Jun 2026 14:11:23 GMT (~1 hour ago)
   **Content**: $IREN $NOW $NFLX $TSLA - just rip off the scab QC
   **Engagement**: 1 like, 0 reposts, 0 replies, 7 views
   **Link**: https://x.com/deplorabletrdr/status/2063624866138300468
   **Sentiment**: Bullish (suggests strong upward move)

3. **@camikingtp** (Michael Taylor)
   **Time**: Sun, 07 Jun 2026 14:11:10 GMT (~1 hour ago)
   **Content**: Trump’s Current Portfolio Just Dropped — And It’s Heavy on AI Winners. … • $TSLA — 9.0% … Load the Trump AI stack before the next leg up. 🚀
   **Engagement**: 0 likes, 0 reposts, 0 replies, 10 views
   **Link**: https://x.com/camikingtp/status/2063624814640640072
   **Sentiment**: Bullish (highlights TSLA in portfolio, calls dip a buying opportunity)

4. **@DanBTC916** (Dan ⚡️)
   **Time**: Sun, 07 Jun 2026 14:10:20 GMT (~1 hour ago)
   **Content**: $TSLA (replying to discussion on SpaceX IPO vs Tesla market cap growth)
   **Engagement**: 2 likes, 0 reposts, 0 replies, 94 views
   **Link**: https://x.com/DanBTC916/status/2063624603612672064
   **Sentiment**: Bullish (prefers TSLA for faster growth)

5. **@Olivia_franzen** (liv franzen)
   **Time**: Sun, 07 Jun 2026 14:09:32 GMT (~1 hour ago)
   **Content**: 🚀 While you’re sleeping, the market is printing. … $TSLA $CRYPTO Stop watching from the sidelines.
   **Engagement**: 0 likes, 0 reposts, 0 replies, 22 views
   **Link**: https://x.com/Olivia_franzen/status/2063624401627595121
   **Sentiment**: Bullish (promotes active trading in TSLA)

6. **@WealthCoachMak** (Coach Mak | Know Your Money)
   **Time**: Sun, 07 Jun 2026 14:07:00 GMT (~1 hour ago)
   **Content**: My rules are simple: … I sell puts on stocks like $NVDA $AMZN $GOOGL $TSLA $AMD $HOOD $PLTR 🔥
   **Engagement**: 0 likes, 0 reposts, 3 replies, 166 views
   **Link**: https://x.com/WealthCoachMak/status/2063623763946516590
   **Sentiment**: Bullish (includes TSLA in options-selling strategy for ownership)

7. **@bloom_rust** (:p)
   **Time**: Sun, 07 Jun 2026 14:06:45 GMT (~1 hour ago)
   **Content**: GM 🍀 … Push $TSLA to the top
   **Engagement**: 0 likes, 0 reposts, 0 replies, 15 views
   **Link**: https://x.com/bloom_rust/status/2063623699966865662
   **Sentiment**: Bullish (calls to boost TSLA ranking/visibility)

8. **@optimus_tsla** (파로호)
   **Time**: Sun, 07 Jun 2026 14:11:05 GMT (~1 hour ago)
   **Content**: [Image post quoting political content, with TSLA handle]
   **Engagement**: 0 likes, 0 reposts, 0 replies, 2 views
   **Link**: https://x.com/optimus_tsla/status/2063624791987458278
   **Sentiment**: Neutral (incidental TSLA mention via handle)

9. **@FrancescoTsla** (Francesco)
   **Time**: Sun, 07 Jun 2026 14:10:53 GMT (~1 hour ago)
   **Content**: [Italian-language post, handle suggests TSLA focus]
   **Engagement**: 0 likes, 0 reposts, 0 replies, 4 views
   **Link**: https://x.com/FrancescoTsla/status/2063624743568216235
   **Sentiment**: Neutral (low relevance to stock)

10. **@hochan_ju97353** (IllllIIlIlIlllll)
    **Time**: Sun, 07 Jun 2026 14:11:56 GMT (~1 hour ago)
    **Content**: 정치 관심없는 배우자가 베스트! (Korean post containing TSLA reference)
    **Engagement**: 0 likes, 0 reposts, 0 replies, 2 views
    **Link**: https://x.com/hochan_ju97353/status/2063625006089937007
    **Sentiment**: Neutral (minimal stock context)

**Overall Sentiment Summary**: Predominantly **bullish** or neutral among the relevant posts, with emphasis on TSLA in AI portfolios, options strategies, and growth comparisons. No strong bearish takes appeared in this window. No major earnings or price-movement discussions surfaced in the top recent results.

In [65]:
# Search with SORT


def get_recent_social_posts_with_xai(ticker: str, max_posts: int = 5, sort_by: str = "engagement"):
    """
    Get recent Twitter/X posts using xAI's Responses API with x_search tool.
    
    Args:
        ticker: Stock ticker symbol
        max_posts: Number of posts to return
        sort_by: "engagement" (views+likes+replies) or "recent" (timestamp)
    """
    
    api_key = os.getenv('XAI_API_KEY')
    if not api_key:
        return {
            'ticker': ticker,
            'error': 'XAI_API_KEY not found. Set it in your .envrc file.',
            'posts': []
        }
    
    try:
        client = openai.OpenAI(
            api_key=api_key,
            base_url="https://api.x.ai/v1"
        )
        
        # Build search query based on sorting preference
        if sort_by == "engagement":
            sort_instruction = """
            IMPORTANT: Sort by HIGHEST ENGAGEMENT (total impact) first.
            - Calculate engagement score = views + likes + replies + retweets
            - Show the posts with highest engagement numbers first
            - These are the most impactful/viral posts about the stock
            """
        else:
            sort_instruction = "Sort by most recent timestamp first."
        
        search_query = f"""
        Search X/Twitter for posts about ${ticker} stock from the last 24 hours.
        
        {sort_instruction}
        
        For each of the {max_posts} posts, provide:
        - Post content
        - Author username
        - Exact engagement metrics: views, likes, replies, retweets, bookmarks
        - Timestamp
        - Real working X.com link
        - Sentiment analysis
        
        Focus on posts with substantial engagement that show real market impact.
        Skip posts with 0 or minimal engagement unless specifically requested.
        
        Format each post clearly showing the engagement numbers prominently.
        """
        
        response = client.responses.create(
            model="grok-4.3",
            input=search_query,
            tools=[{"type": "x_search"}]
        )
        
        # Extract response content
        content = ""
        for item in response.output:
            if item.type == "message":
                for content_block in item.content:
                    if content_block.type == "output_text":
                        content += content_block.text
        
        return {
            'ticker': ticker,
            'response': content,
            'posts': [],
            'sort_by': sort_by,
            'timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            'api_used': 'responses_api_with_x_search'
        }
        
    except openai.AuthenticationError:
        return {
            'ticker': ticker,
            'error': 'Authentication failed. Check your XAI_API_KEY.',
            'posts': []
        }
    
    except openai.RateLimitError:
        return {
            'ticker': ticker,
            'error': 'Rate limit exceeded. Try again later.',
            'posts': []
        }
    
    except Exception as e:
        return {
            'ticker': ticker,
            'error': f'API error: {str(e)}',
            'posts': []
        }

# Function for high-engagement posts specifically
def get_viral_social_posts(ticker: str, max_posts: int = 5, min_engagement: int = 100):
    """
    Get posts with high engagement (viral posts) about a stock.
    """
    
    api_key = os.getenv('XAI_API_KEY')
    if not api_key:
        return {
            'ticker': ticker,
            'error': 'XAI_API_KEY not found',
            'posts': []
        }
    
    try:
        client = openai.OpenAI(
            api_key=api_key,
            base_url="https://api.x.ai/v1"
        )
        
        viral_search_query = f"""
        Search X/Twitter for HIGH-ENGAGEMENT posts about ${ticker} stock from the last 48 hours.
        
        CRITERIA:
        - Only show posts with {min_engagement}+ total engagement (views + likes + replies + retweets)
        - Sort by HIGHEST engagement first (most viral/impactful)
        - Focus on posts that are actually moving opinions or generating discussion
        - Skip spam, bot posts, or posts with minimal engagement
        
        Return the top {max_posts} most viral posts with:
        - Total engagement score prominently displayed
        - Post content 
        - Author (prioritize verified accounts, influencers, analysts)
        - All engagement metrics broken down
        - Working X.com links
        - Why this post is significant/viral
        
        These should be posts that are actually influencing ${ticker} sentiment in the market.
        """
        
        response = client.responses.create(
            model="grok-4.3",
            input=viral_search_query,
            tools=[{"type": "x_search"}]
        )
        
        # Extract content
        content = ""
        for item in response.output:
            if item.type == "message":
                for content_block in item.content:
                    if content_block.type == "output_text":
                        content += content_block.text
        
        return {
            'ticker': ticker,
            'response': content,
            'posts': [],
            'search_type': 'viral_posts',
            'min_engagement': min_engagement,
            'timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        }
        
    except Exception as e:
        return {
            'ticker': ticker,
            'error': f'Error: {str(e)}',
            'posts': []
        }

In [66]:
print("=== Testing Engagement-Sorted Posts ===")
result1 = get_recent_social_posts_with_xai("TSLA", 5, sort_by="engagement")
if 'error' in result1:
    print(f"❌ Error: {result1['error']}")
else:
    print(f"✅ Success - sorted by {result1['sort_by']}")
    print("Top engagement posts:")

=== Testing Engagement-Sorted Posts ===
✅ Success - sorted by engagement
Top engagement posts:

In [67]:
print(result1['response'])

**Top 5 most impactful $TSLA posts from the last 24 hours** (sorted by highest engagement score = views + likes + replies + reposts/retweets). All have substantial engagement.

### 1. Highest Engagement Post
**Engagement Score: 32,232**
**Views: 31,921 | Likes: 248 | Replies: 41 | Reposts: 22 | Bookmarks: 19**
**Author:** @M44_1RJ (Jimmy)
**Timestamp:** Sat, 06 Jun 2026 15:57:12 GMT
**Content:** For all my $TSLA followers or non-$TSLA followers, All you need to know is: Tesla stock is going to $850-$1000 in 12 months!! That’s all you need to know — what happens between now and then is just noise and opportunities for you to choose. Be sure to follow the right accounts. I have 14 years into this — heavy shareholder 🐳 and elite Algo L4 fractal analyst (more than EW studies).
**X.com Link:** https://x.com/M44_1RJ/status/2063289110350254256
**Sentiment:** Strongly Bullish (price target of $850–$1,000 in 12 months)

### 2. Second Highest
**Engagement Score: 3,816**
**Views: 3,770 | Likes: 32 | Replies: 13 | Reposts: 1 | Bookmarks: 0**
**Author:** @kylaschwaberow (Pete Balls to the wall FSD 🤖🚕)
**Timestamp:** Sun, 07 Jun 2026 07:34:29 GMT
**Content:** What looks more bullish, $TSLA or bitcoin:native ? (with 2 images)
**X.com Link:** https://x.com/kylaschwaberow/status/2063524982995738679
**Sentiment:** Bullish (comparing $TSLA favorably to Bitcoin)

### 3. Third Highest
**Engagement Score: 2,164**
**Views: 2,115 | Likes: 45 | Replies: 1 | Reposts: 3 | Bookmarks: 0**
**Author:** @bradsferguson (Bradford Ferguson)
**Timestamp:** Sat, 06 Jun 2026 14:45:49 GMT
**Content:** We’re All-In. Stop by the @Rebellionaire booth at the Michigan Summer Meetup ⚡️ $TSLA (with image)
**X.com Link:** https://x.com/bradsferguson/status/2063271145164489073
**Sentiment:** Strongly Bullish (“All-In” on $TSLA)

### 4. Fourth Highest
**Engagement Score: 1,915**
**Views: 1,795 | Likes: 95 | Replies: 20 | Reposts: 5 | Bookmarks: 2**
**Author:** @M44_1RJ (Jimmy)
**Timestamp:** Sat, 06 Jun 2026 18:05:52 GMT
**Content:** Coffee on the beach 🏖️!! The day $TSLA hit $1000 I will invite my loyal subs & followers to Kauai for a 3-day weekend retreat!! !!! So get ready peeps and be my wingman !! 😎🙌🐳🦁 (with image)
**X.com Link:** https://x.com/M44_1RJ/status/2063321489055883564
**Sentiment:** Strongly Bullish ($1,000 price target + celebratory tone)

### 5. Fifth Highest
**Engagement Score: 775**
**Views: 767 | Likes: 7 | Replies: 1 | Reposts: 0 | Bookmarks: 0**
**Author:** @Redbull_kr_7 (Red_Jerry)
**Timestamp:** Sun, 07 Jun 2026 02:02:04 GMT
**Content:** $TSLA 내일 국장과 미장 너무나 기대되는걸?! 내일은 장 안보고 그냥 운동하고 일찍 뻗는게 정신건강에 좋을듯
**X.com Link:** https://x.com/Redbull_kr_7/status/2063441328919421156
**Sentiment:** Bullish (expressing excitement for tomorrow’s US & Korean markets)

In [68]:
print("\n=== Testing Viral Posts (High Engagement Only) ===")
result2 = get_viral_social_posts("TSLA", 5, min_engagement=100)
if 'error' in result2:
    print(f"❌ Error: {result2['error']}")
else:
    print(f"✅ Success - viral posts with 50+ engagement")
    print("Viral posts:")

=== Testing Viral Posts (High Engagement Only) ===
✅ Success - viral posts with 50+ engagement
Viral posts:

In [69]:
print(result1['response'])

**Top 5 most impactful $TSLA posts from the last 24 hours** (sorted by highest engagement score = views + likes + replies + reposts/retweets). All have substantial engagement.

### 1. Highest Engagement Post
**Engagement Score: 32,232**
**Views: 31,921 | Likes: 248 | Replies: 41 | Reposts: 22 | Bookmarks: 19**
**Author:** @M44_1RJ (Jimmy)
**Timestamp:** Sat, 06 Jun 2026 15:57:12 GMT
**Content:** For all my $TSLA followers or non-$TSLA followers, All you need to know is: Tesla stock is going to $850-$1000 in 12 months!! That’s all you need to know — what happens between now and then is just noise and opportunities for you to choose. Be sure to follow the right accounts. I have 14 years into this — heavy shareholder 🐳 and elite Algo L4 fractal analyst (more than EW studies).
**X.com Link:** https://x.com/M44_1RJ/status/2063289110350254256
**Sentiment:** Strongly Bullish (price target of $850–$1,000 in 12 months)

### 2. Second Highest
**Engagement Score: 3,816**
**Views: 3,770 | Likes: 32 | Replies: 13 | Reposts: 1 | Bookmarks: 0**
**Author:** @kylaschwaberow (Pete Balls to the wall FSD 🤖🚕)
**Timestamp:** Sun, 07 Jun 2026 07:34:29 GMT
**Content:** What looks more bullish, $TSLA or bitcoin:native ? (with 2 images)
**X.com Link:** https://x.com/kylaschwaberow/status/2063524982995738679
**Sentiment:** Bullish (comparing $TSLA favorably to Bitcoin)

### 3. Third Highest
**Engagement Score: 2,164**
**Views: 2,115 | Likes: 45 | Replies: 1 | Reposts: 3 | Bookmarks: 0**
**Author:** @bradsferguson (Bradford Ferguson)
**Timestamp:** Sat, 06 Jun 2026 14:45:49 GMT
**Content:** We’re All-In. Stop by the @Rebellionaire booth at the Michigan Summer Meetup ⚡️ $TSLA (with image)
**X.com Link:** https://x.com/bradsferguson/status/2063271145164489073
**Sentiment:** Strongly Bullish (“All-In” on $TSLA)

### 4. Fourth Highest
**Engagement Score: 1,915**
**Views: 1,795 | Likes: 95 | Replies: 20 | Reposts: 5 | Bookmarks: 2**
**Author:** @M44_1RJ (Jimmy)
**Timestamp:** Sat, 06 Jun 2026 18:05:52 GMT
**Content:** Coffee on the beach 🏖️!! The day $TSLA hit $1000 I will invite my loyal subs & followers to Kauai for a 3-day weekend retreat!! !!! So get ready peeps and be my wingman !! 😎🙌🐳🦁 (with image)
**X.com Link:** https://x.com/M44_1RJ/status/2063321489055883564
**Sentiment:** Strongly Bullish ($1,000 price target + celebratory tone)

### 5. Fifth Highest
**Engagement Score: 775**
**Views: 767 | Likes: 7 | Replies: 1 | Reposts: 0 | Bookmarks: 0**
**Author:** @Redbull_kr_7 (Red_Jerry)
**Timestamp:** Sun, 07 Jun 2026 02:02:04 GMT
**Content:** $TSLA 내일 국장과 미장 너무나 기대되는걸?! 내일은 장 안보고 그냥 운동하고 일찍 뻗는게 정신건강에 좋을듯
**X.com Link:** https://x.com/Redbull_kr_7/status/2063441328919421156
**Sentiment:** Bullish (expressing excitement for tomorrow’s US & Korean markets)

In [74]:
import os
from datetime import datetime
import openai

def get_reddit_stock_discussions(ticker: str, max_posts: int = 5, min_engagement: int = 50):
    """
    Get high-engagement Reddit discussions about a stock using web_search.
    """
    
    api_key = os.getenv('XAI_API_KEY')
    if not api_key:
        return {
            'ticker': ticker,
            'error': 'XAI_API_KEY not found. Set it in your .envrc file.',
            'posts': []
        }
    
    try:
        client = openai.OpenAI(
            api_key=api_key,
            base_url="https://api.x.ai/v1"
        )
        
        # Reddit-focused search query
        reddit_query = f"""
        Search Reddit for high-quality discussions about ${ticker} stock from the last 7 days.
        
        **TARGET SUBREDDITS (search these specifically):**
        - r/investing (serious investment analysis)
        - r/stocks (general stock discussion)
        - r/SecurityAnalysis (fundamental analysis)
        - r/ValueInvesting (value perspective)
        - r/wallstreetbets (retail sentiment & options)
        - r/StockMarket (market discussion)
        - r/financialindependence (long-term investing)
        - Ticker-specific subs if they exist (like r/Tesla for TSLA)
        
        **ENGAGEMENT CRITERIA:**
        - Posts with {min_engagement}+ upvotes OR 30+ comments
        - Comments with 20+ upvotes
        - Awarded posts (Gold, Silver, Helpful, etc.)
        - Active discussions (not just single comments)
        
        **CONTENT TYPES TO PRIORITIZE:**
        1. DD (Due Diligence) posts with detailed analysis
        2. Earnings reaction/discussion threads
        3. News reaction posts with substantial comments
        4. Technical/fundamental analysis posts
        5. Company catalyst discussions
        6. Valuation debates
        
        **OUTPUT FORMAT for each post:**
        
        **[Subreddit Name]** - Post Title
        **Content:** Brief summary of post + key insights from top comments
        **Stats:** X upvotes, Y comments, Z awards
        **Link:** Direct Reddit URL
        **Sentiment:** Bullish/Bearish/Neutral with reasoning
        **Key Points:** 2-3 main takeaways from the discussion
        **Quality Level:** High/Medium (based on depth of analysis)
        
        Return the {max_posts} most valuable Reddit discussions about ${ticker}, sorted by engagement and discussion quality.
        Focus on posts that provide real investment insights, not just price speculation.
        """
        
        response = client.responses.create(
            model="grok-4.3",
            input=reddit_query,
            tools=[{"type": "web_search"}]
        )
        
        # Extract content
        content = ""
        for item in response.output:
            if item.type == "message":
                for content_block in item.content:
                    if content_block.type == "output_text":
                        content += content_block.text
        
        return {
            'ticker': ticker,
            'response': content,
            'posts': [],
            'platform': 'Reddit',
            'min_engagement': min_engagement,
            'search_timeframe': 'last_7_days',
            'timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        }
        
    except openai.AuthenticationError:
        return {
            'ticker': ticker,
            'error': 'Authentication failed. Check your XAI_API_KEY.',
            'posts': []
        }
    
    except openai.RateLimitError:
        return {
            'ticker': ticker,
            'error': 'Rate limit exceeded. Try again later.',
            'posts': []
        }
    
    except Exception as e:
        return {
            'ticker': ticker,
            'error': f'API error: {str(e)}',
            'posts': []
        }

# Specialized function for DD posts only
def get_reddit_dd_posts(ticker: str, max_posts: int = 3):
    """
    Get only DD (Due Diligence) posts about a stock from Reddit.
    """
    
    api_key = os.getenv('XAI_API_KEY')
    if not api_key:
        return {
            'ticker': ticker,
            'error': 'XAI_API_KEY not found',
            'posts': []
        }
    
    try:
        client = openai.OpenAI(
            api_key=api_key,
            base_url="https://api.x.ai/v1"
        )
        
        dd_query = f"""
        Search Reddit specifically for DD (Due Diligence) posts about ${ticker} stock.
        
        **SEARCH FOCUS:**
        - Look for posts tagged with "DD" or containing detailed financial analysis
        - Search r/investing, r/SecurityAnalysis, r/ValueInvesting, r/stocks
        - Find posts with comprehensive company analysis, not just opinions
        
        **DD POST CRITERIA:**
        - Contains financial metrics, ratios, or analysis
        - Discusses business fundamentals, competition, or growth prospects
        - Has substantial content (not just a few paragraphs)
        - Generated meaningful discussion in comments
        
        **OUTPUT for each DD post:**
        
        **[Subreddit]** - DD Title
        **Author:** Username (mention if they have credibility/history)
        **Analysis Summary:** Key points from the DD (financials, valuation, thesis)
        **Community Response:** Top comments reactions, counterpoints, additional insights
        **Stats:** Upvotes, comments, awards
        **Link:** Reddit URL
        **Investment Thesis:** Bull/bear case summary
        **Quality Score:** High/Medium/Low based on depth and accuracy
        
        Return the {max_posts} highest quality DD posts about ${ticker} from the last 30 days.
        """
        
        response = client.responses.create(
            model="grok-4.3",
            input=dd_query,
            tools=[{"type": "web_search"}]
        )
        
        # Extract content
        content = ""
        for item in response.output:
            if item.type == "message":
                for content_block in item.content:
                    if content_block.type == "output_text":
                        content += content_block.text
        
        return {
            'ticker': ticker,
            'response': content,
            'posts': [],
            'search_type': 'dd_posts_only',
            'platform': 'Reddit',
            'timestamp': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        }
        
    except Exception as e:
        return {
            'ticker': ticker,
            'error': f'Error: {str(e)}',
            'posts': []
        }

In [75]:

# Test the Reddit functions
print("=== Testing Reddit Stock Discussions ===")
result4 = get_reddit_stock_discussions("TSLA", 5, min_engagement=50)

if 'error' in result4:
    print(f"❌ Error: {result4['error']}")
else:
    print(f"✅ Success for {result4['ticker']} on {result4['platform']}")
    print(f"Min engagement: {result4['min_engagement']}")
    print(f"Timeframe: {result4['search_timeframe']}")
    print("\nReddit discussions:")
    print(result4['response'])

=== Testing Reddit Stock Discussions ===
✅ Success for TSLA on Reddit
Min engagement: 50
Timeframe: last_7_days

Reddit discussions:
**Here are the 5 most valuable recent Reddit discussions on $TSLA (primarily from the last ~7 days, centered on June 2026 context) from the targeted subreddits.** These focus on valuation debates, SpaceX IPO/merger implications, analyst actions, and fundamental analysis rather than pure price speculation. Results are drawn from web searches emphasizing high-engagement threads in r/stocks, r/StockMarket, r/wallstreetbets, and r/ValueInvesting (limited direct hits in stricter value/ investing subs). Engagement is inferred from visible comment scores and discussion depth in results.[[1]](https://www.reddit.com/r/StockMarket/comments/1tu345u/elon_musk_wants_to_merge_spacex_and_tesla_into_a/)[[2]](https://www.reddit.com/r/stocks/comments/1tv5ykp/spacex_valued_at_just_780_billion_by_morningstar/)

**Note:** Pure TSLA-only threads were overshadowed by SpaceX-IPO news and its overlap with Tesla (e.g., potential merger, relative valuations, hype vs. fundamentals). No strong recent earnings threads appeared in results.

**[r/StockMarket] - Elon Musk wants to merge SpaceX and Tesla into a $3.4 trillion giant. The problem: it would lose money from day one.**
**Content:** Discussion of Musk potentially using an overvalued SpaceX IPO (~$1.75T target) to acquire or merge with TSLA (~$1.6T), including analyst views (e.g., New Constructs' David Trainer) that this could "bail out" TSLA shareholders amid dwindling profits and high valuation. Top comments highlight TSLA's extreme P/E (~500 or forward ~150), overvaluation risks, and historical parallels like SolarCity.
**Stats:** Multiple comments with 70+ upvotes; active thread with 100+ comments.
**Link:** https://www.reddit.com/r/StockMarket/comments/1tu345u/elon_musk_wants_to_merge_spacex_and_tesla_into_a/
**Sentiment:** Bearish/Neutral (skeptical of merger as a fix).
**Key Points:** TSLA valuation appears unsustainable without external "bailout"; SpaceX hype could prop it up short-term but risks major selloff; conventional metrics (P/E, profits) don't support current levels.
**Quality Level:** High (detailed analyst references and logical valuation critique).[[1]](https://www.reddit.com/r/StockMarket/comments/1tu345u/elon_musk_wants_to_merge_spacex_and_tesla_into_a/)

**[r/stocks] - SpaceX valued at just $780 billion by Morningstar, less than half its IPO target.**
**Content:** Analysis of Morningstar's narrow-moat $400 fair value for TSLA (vs. current much higher price) alongside a conservative $780B SpaceX valuation. Comments debate analyst credibility (e.g., single analyst coverage), TSLA's P/E of ~383, and whether hype justifies premiums.
**Stats:** Comments scoring 30+ upvotes; substantial back-and-forth.
**Link:** https://www.reddit.com/r/stocks/comments/1tv5ykp/spacex_valued_at_just_780_billion_by_morningstar/
**Sentiment:** Bearish on TSLA valuation.
**Key Points:** Professional fair-value estimates lag market prices significantly for both companies; TSLA's moat and growth assumptions questioned; Morningstar views seen as more defensible than hype-driven targets.
**Quality Level:** High (fundamentals-focused with specific metrics).[[2]](https://www.reddit.com/r/stocks/comments/1tv5ykp/spacex_valued_at_just_780_billion_by_morningstar/)

**[r/wallstreetbets] - JP Morgan upgrades Tesla to 'neutral', sees robotics...**
**Content:** Reaction to JPMorgan's TSLA upgrade to neutral with robotics/AI upside noted, contrasted against prior warnings of potential 60% downside. Retail sentiment mixes option plays with longer-term skepticism.
**Stats:** Active WSB-style discussion (high comment volume implied by context).
**Link:** https://www.reddit.com/r/wallstreetbets/comments/1txf152/jp_morgan_upgrades_tesla_to_neutral_sees_robotics/
**Sentiment:** Mixed/Neutral (upgrade tempered by downside risks).
**Key Points:** Analyst shifts reflect robotics catalyst potential but don't override valuation concerns; options liquidity in TSLA highlighted for short-term trades.
**Quality Level:** Medium (more sentiment/options-focused than deep DD).[[3]](https://www.reddit.com/r/wallstreetbets/comments/1txf152/jp_morgan_upgrades_tesla_to_neutral_sees_robotics/)

**[r/stocks] - SpaceX targets $135 IPO price at valuation of $1.77 trillion.**
**Content:** Breakdown of SpaceX's IPO plans (Nasdaq debut June 12, massive raise) and implications for TSLA (potential merger chatter, relative valuations). Users compare fundamentals (e.g., SpaceX losses vs. growth bets) and question sustainability at these levels.
**Stats:** Comments with 40+ upvotes; detailed replies on growth needs and hype.
**Link:** https://www.reddit.com/r/stocks/comments/1tw27pr/spacex_targets_135_ipo_price_at_valuation_of_177/
**Sentiment:** Neutral to Bearish on sustainability.
**Key Points:** SpaceX valuation dwarfs TSLA despite losses; merger could be a lifeline but hinges on belief in future narratives (space mining, AI); TSLA's current price seen as detached from near-term profits.
**Quality Level:** High (IPO mechanics + comparative analysis).[[4]](https://www.reddit.com/r/stocks/comments/1tw27pr/spacex_targets_135_ipo_price_at_valuation_of_177/)

**[r/stocks] - The "bull case" for SpaceX: re-running the Tesla dilution...** (and related ValueInvesting threads on SpaceX growth needs).
**Content:** Explores how TSLA's valuation has been sustained by narrative/hype despite flat revenues/profits; applies similar logic to SpaceX IPO. Parallel threads discuss needing 60x growth or extreme multiples to justify targets.
**Stats:** Engaged comments (20+ upvotes common); cross-sub discussion.
**Link:** https://www.reddit.com/r/stocks/comments/1tzlo3d/the_bull_case_for_spacex_rerunning_the_tesla/ (see also r/ValueInvesting examples).
**Sentiment:** Skeptical/Bearish on pure fundamentals.
**Key Points:** TSLA precedent shows narrative can override metrics short-term; SpaceX requires massive execution to justify IPO price; long-term holders advised caution vs. safer growth names.
**Quality Level:** High (thematic DD tying two companies).[[5]](https://www.reddit.com/r/stocks/comments/1tzlo3d/the_bull_case_for_spacex_rerunning_the_tesla/)

These threads emphasize **fundamental valuation debates, analyst inputs, and merger/IPO catalysts** over meme-driven speculation. SpaceX news dominated recent $TSLA discourse due to shared Musk ownership and potential synergies. For deeper dives, visit the links directly as Reddit content evolves quickly.

In [ ]:
print("\n=== Testing DD Posts Only ===")
dd_result = get_reddit_dd_posts("TSLA", 2)

if 'error' in dd_result:
    print(f"❌ Error: {dd_result['error']}")
else:
    print(f"✅ Success - {dd_result['search_type']}")
    print("DD posts preview:")
    print(dd_result['response'])

=== Testing DD Posts Only ===
✅ Success - dd_posts_only
DD posts preview:
**No qualifying DD posts about $TSLA matching the specified criteria were found in the last 30 days (approximately May 9–June 8, 2026) across r/investing, r/SecurityAnalysis, r/ValueInvesting, or r/stocks.**[[1]](https://www.reddit.com/r/stocks/comments/1tdely5/unusual_machines_umac_posts_quarterly_results/)[[2]](https://www.reddit.com/r/investing/comments/1tp4x54/are_there_any_pro_investment_arguments_for_spacex/)

Extensive web searches using targeted operators (site:reddit.com restrictions to the listed subreddits, keywords like "DD", "due diligence", "financial analysis", "valuation", "fundamentals", combined with 2026 date signals) returned no posts with substantial financial metrics, business fundamentals analysis, competition/growth prospects discussion, or meaningful comment engagement that fit the DD criteria.[[3]](https://www.reddit.com/r/stocks/comments/1sjecim/tsla_at_190_is_not_a_prediction_its_just_math/)[[4]](https://www.reddit.com/r/teslainvestorsclub/comments/1kv8a6a/full_length_tesla_dd_and_analysis/)

- Mentions of TSLA appear in passing (e.g., valuation comparisons or tangential comments in other threads), but these lack comprehensive analysis, substantial length, or dedicated DD structure.[[5]](https://www.reddit.com/r/stocks/comments/1t5hxu0/intel_trading_at_a_119x_forward_pe_and_nobody_is/)
- Older or non-subreddit posts (e.g., in r/teslainvestorsclub) exist but fall outside the date range, focus subreddits, or depth requirements.[[4]](https://www.reddit.com/r/teslainvestorsclub/comments/1kv8a6a/full_length_tesla_dd_and_analysis/)

If new posts appear or broader searches (e.g., additional subreddits or relaxed criteria) are needed, provide more details for further investigation. Always verify current Reddit content directly, as search indexing can lag.